name: Release and publish to NPM registry

on:
  ## Allow triggering this workflow manually via GitHub CLI/web
  workflow_dispatch:

  ## Run this workflow whenever a push to the master branch is made
  push:
    branches:
      - main

jobs:
  test_unix:
    timeout-minutes: 3
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        shell: [sh, bash]
        os: [macos-latest, ubuntu-latest]
    defaults:
      run:
        shell: ${{ matrix.shell }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: npm
      - run: npm ci
        env:
          NODE_ENV: development
      - run: npm run build
      - run: npm start
  ## A dedicated job for Windows because it supports a bunch of shells that are not available for other OS
  test_windows:
    timeout-minutes: 3
    runs-on: windows-latest
    strategy:
      matrix:
        shell: [pwsh, cmd, PowerShell]
    defaults:
      run:
        shell: ${{ matrix.shell }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: npm
      - run: npm ci
        env:
          NODE_ENV: development
      - run: npm run build
      - run: npm start

  release:
    needs: [test_unix, test_windows]
    timeout-minutes: 3
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: npm
      - run: npm ci
        env:
          NODE_ENV: development
      - run: npm run build
      - run: npm run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
